apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f /usr/src/app/media/uploads/docker-compose/b2fbe08d-c21c-497d-914e-1a3281443b51.yaml
        -o media/uploads/docker-compose/40d93610-33cf-48b3-8b29-003aae6699ef
      kompose.version: 1.8.0 (0c0c027)
    creationTimestamp: null
    labels:
      io.kompose.service: nervous-perf
    name: nervous-perf
  spec:
    ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    selector:
      io.kompose.service: nervous-perf
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f /usr/src/app/media/uploads/docker-compose/b2fbe08d-c21c-497d-914e-1a3281443b51.yaml
        -o media/uploads/docker-compose/40d93610-33cf-48b3-8b29-003aae6699ef
      kompose.version: 1.8.0 (0c0c027)
    creationTimestamp: null
    labels:
      io.kompose.service: nervous-perf
    name: nervous-perf
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: nervous-perf
      spec:
        containers:
        - image: iperf
          name: iperf-container
          ports:
          - containerPort: 5001
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
